### ISSUE TITLE
using AMP API

### ISSUE THREAD

**Issue by markus2120** [heubergen/amplifier-firefox#2]
For many websites it would be better to load from google CDN (yes yes, I know some people have privacy issues, but google CDN loads in https and not http so at least your DSL/wifi provider cannot know your URL - does not load many other trackers). See here. https://developers.google.com/amp/cache/reference/acceleratedmobilepageurl/rest/
it would be nice of you can use the API to get the CDN-AMP-URL for the current URL and load it. It loads superfast.

https://developers.google.com/amp/cache/use-amp-url

**Comment by heubergen** [comment]
I'm not a big fan of how Google treats an open framework like it would own it. [[1](https://80x24.net/post/the-problem-with-amp/)][[2](https://danielmiessler.com/blog/google-amp-not-good-thing)] So not, I'll not supporting here Google and helping them to lock down the internet!
